baseURL = 'https://woojae.github.io/woojae.com'
languageCode = 'en-us'
title = 'Woojae.com'
theme = 'maverick'


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = -200